version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hnsqyzn5wr1u"
s3_prefix = "sam-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

